# Generated by Django 5.0.4 on 2024-04-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_category_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Цена за покупку'),
        ),
    ]
