# Generated by Django 5.0.4 on 2024-04-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_time_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
