# Generated by Django 5.0.4 on 2024-04-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufactured_at',
            field=models.TextField(max_length=100, null=True, verbose_name='Модель продукта'),
        ),
    ]
